### ISSUE TITLE
Please disable notifying the upstream IRC channel for your own CI 

### ISSUE THREAD

**Issue by abucodonosor** [manjaro/calamares#26]
Hi @philmmanjaro ,

please change or disable 'chat.freenode.net#calamares'  in your 
travis.yml file for all your branches.

There was an discuss about this on #calamares also see: 
https://github.com/calamares/calamares/pull/835

**Comment by hphilm** [comment]
https://github.com/manjaro/calamares/commit/e43de173d26bccf79e005e58917d6719269dc372
https://github.com/manjaro/calamares/commit/1396e215c9eee0a67fe66dd4184d372c2a3180f9
